server:
  port: 5002

spring:
  application:
    name: "USER-SERVICE"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/tm_task_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

